// src/install/enums/error-codes.enum.ts

export enum ErrorCode {
  PERMISSION_DENIED = "EACCES",
  NETWORK_ERROR = "ENETUNREACH",
  FILE_NOT_FOUND = "ENOENT",
  CHECKSUM_MISMATCH = "CHECKSUM_MISMATCH",
  UNSUPPORTED_PLATFORM = "UNSUPPORTED_PLATFORM",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}
