name: Publish to NPM

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      bump:
        description: 'The type of version bump: patch, minor, major'
        required: false
        default: 'patch'

  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the package
        run: npm run build

      - name: Authenticate with npm registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
