name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      bump:
        description: 'The type of version bump: patch, minor, major'
        required: false
        default: 'patch'

  workflow_run:
    workflows: ['CI']
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write # Required for pushing tags
      issues: write # Required for creating issues on failure
      packages: write # Required for publishing to GitHub Packages
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Build the package
        run: npm run build

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
